# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/civicpulse_db
spring.datasource.username=postgres
spring.datasource.password=Nanaji@2023

# Hibernate Auto Table Creation & Logging
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080